# Generated by Django 6.0.1 on 2026-02-20 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_sellerverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerverification',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='verification_date',
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id_card_back',
            field=models.ImageField(default=None, upload_to='verification/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id_card_front',
            field=models.ImageField(default=None, upload_to='verification/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
