# Generated by Django 6.0.1 on 2026-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_sellerverification_activate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
